# Generated by Django 5.2.1 on 2025-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlproject',
            name='created_at',
        ),
        migrations.AddField(
            model_name='mlproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='mlproject',
            name='github_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='mlproject',
            name='tech_stack',
            field=models.CharField(max_length=200),
        ),
    ]
