# Generated by Django 5.2.1 on 2025-05-30 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_mlproject_created_at_mlproject_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
